Feature/service and path
c-3lab/StarSeeker pull request #19
Opened 2022-12-20 06:58 UTC by mkyutani

Support multitenancy and entity service paths.

- mltitenancy: t_tenant table; fiware-service http header (nodef, nodeb, and orion)
- entity service paths: t_service_path table; fiware-servicepath http header (nodef, nodeb, and orion)
- category (t_category table) depends on the entity service path which depends on the tenant
- Default tenant and service path: NULL in t_tenant, and (NULL, NULL) in t_service_path

2022-12-27 02:44 UTC, ryo-ma requested changes

2022-12-27 02:53 UTC, mkyutani commented on StarSeeker/backend/src/points/points.service.ts
> +    let headers
ありがとうございます。
そのほうがいいですね！

2022-12-27 02:54 UTC, mkyutani commented on StarSeeker/backend/src/categories/categories.service.ts
> +
おっしゃる通りです！

2023-01-02 06:21 UTC, mkyutani commented on StarSeeker/backend/src/categories/categories.service.ts
> +
対応しました。

2023-01-02 06:21 UTC, mkyutani commented on StarSeeker/backend/src/points/points.service.ts
> +    let headers
対応しました。

2023-01-03 01:01 UTC, ryo-ma commented on StarSeeker/backend/src/categories/categories.service.ts
> +
すいません、上記この'query'をconstと記載しましたがletで宣言してした方がよかったかもしれませんね。そうすると`query0`、`query1`、`query2`を宣言する必要がなくなるのでシンプルです。
```
    let query = this.categoryRepository
          .createQueryBuilder('category')
          .leftJoinAndSelect('category.servicePath', 'servicePath')
          .leftJoinAndSelect('servicePath.tenant', 'tenant')
          .leftJoinAndSelect('category.pointDatasets', 'pointDataset')
          .leftJoinAndSelect('category.surfaceDatasets', 'surfaceDataset')
    if (!tenantName) {
        query = query.where('tenant.name IS NULL')
    } else {
        query = query.where('tenant.name = :tenantName', { tenantName: tenantName })
    }
............
    categories = await query.andWhere(new Brackets(queryOr => {
        queryOr.where('pointDataset.enabled = true')
          .orWhere('surfaceDataset.enabled = true')
    })).getMany()
```

2023-01-04 01:29 UTC, mkyutani commented on StarSeeker/backend/src/categories/categories.service.ts
> +
あ、そうか・・・`let`ならば何度も値を変更できますね。

2023-01-04 02:05 UTC, mkyutani commented on StarSeeker/backend/src/categories/categories.service.ts
> +
対応しました。
eslintをかけたので(?)タブ→空白や末尾コンマ削除など細かい変更が入ってしまっていますが・・・

2023-01-04 03:07 UTC, ryo-ma commented
# LGTM!!
![](https://media.giphy.com/media/LRULWKohBXeaeGBJKH/giphy.gif)

2023-01-04 03:18 UTC, ryo-ma approved these changes

2023-01-04 03:18 UTC, merged